main : com.tistory.ksnd0297.CloneEssential.CloneEssentialMain
name : CloneEssential
version : 1.0.0
author : ksnd0297
description : Clone_Essential_Plugin
commands :
  날씨 :
    description : 클론에센셜_날씨
    usage : /날씨 [명령어]
  순간이동 :
    description : 클론에센셜_순간이동
    usage : /순간이동 [이름]
  시간 :
    description : 클론에센셜_시간
    usage : /시간 설정 [틱]
  스폰 :
    description : 클론에센셜_스폰
    usage : /스폰 [지정 or 이동]