main : com.tistory.ksnd0297.main.CloneEssentialMain
name : CloneEssential
version : 1.0.0
author : ksnd0297
description : Clone_Essential_Plugin
commands :
  날씨 :
    description : 클론에센셜_날씨
    usage : /날씨 [맑음 | 비 | 천둥]
  시간 :
    description : 클론에센셜_시간
    usage : /시간 [아침 | 점심 | 저녁 | 새벽]
  홈 :
    description : 클론에센셜_홈
    usage : /홈 [지정 | 이동]
  스폰 :
    description : 클론에센셜_스폰
    usage : /스폰 [지정 | 이동]
  게임모드 :
    description : 클론에센셜_게임모드
    usage : /게임모드 [크리에이티브 | 서바이벌]
  텔레포트 :
    description : 클론에센셜_텔레포트
    usage : /텔레포트 [대상]
  난이도 :
    description : 클론에센셜_난이도
    usage : /난이도 [평화로움 | 쉬움 | 보통 | 어려움]
  배고픔 :
    description : 클론에센셜_배고픔
    usage : /배고픔 [0 ~ 10]
  체력 :
    description : 클론에센셜_체력
    usage : /체력 [0 ~ 20]
  자살 :
    description : 클론에센셜_자살
    usage : /자살