main : com.tistory.ksnd0297.main.CloneEssentialMain
name : CloneEssential
version : 1.0.0
author : ksnd0297
description : Clone_Essential_Plugin
commands :
  날씨 :
    description : 클론에센셜_날씨
    usage : /날씨 [맑음 | 비 | 천둥]
  시간 :
    description : 클론에센셜_시간
    usage : /시간 [아침 | 점심 | 저녁 | 새벽]
  홈 :
    description : 클론에센셜_스폰
    usage : /홈 [지정 | 이동]