main : ksnd0297.main.PraticePluginMain
name : PraticePlugin
version : 1.0.0
author : ksnd0297
description : Pratice_Plugin
commands : 
  도끼 :
    description : WorldEdit 도끼 지급
    usage : /도끼
  채우기 :
    description : WorldEdit 도끼 채우기
    usage : /채우기 블록